name: first_flutter_web_app
description: An app built using Flutter for web

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/rotateNintyDegrees.R

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.0.0
  charts_flutter: ^0.8.1
  numberpicker: ^1.1.0
  hive_flutter: ^0.2.1
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
